# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.17'
auto_detect_solc = false
optimizer_runs = 1_000_000
verbosity = 1

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/hvzAMYtUqrct8UnhHpi5tqPiAodbf-OP"
